name: Apple Store Monitor
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5 # v4 から v5 へ
      - name: Set up Python
        uses: actions/setup-python@v5 # v4 から v5 へ
        with:
          python-version: '3.11' # ついでにPythonも新しめに
      - name: Install dependencies
        run: pip install requests
      - env:
          LINE_ACCESS_TOKEN: ${{ secrets.LINE_ACCESS_TOKEN }}
          USER_ID: ${{ secrets.USER_ID }}
        run: python main.py
