name: Apple Store Monitor
on:
  schedule:
    - cron: '*/15 * * * *' # 15分おきに実行
  workflow_dispatch: # 手動実行ボタンも作る

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests
      - env:
          LINE_ACCESS_TOKEN: ${{ secrets.LINE_ACCESS_TOKEN }}
          USER_ID: ${{ secrets.USER_ID }}
        run: python main.py
